"""added blacklisted tokens

Revision ID: 427e6fb33b3d
Revises: 82e036d8a1a6
Create Date: 2025-02-12 22:38:51.248694
"""

from typing import Sequence, Union
from alembic import op
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "427e6fb33b3d"
down_revision: Union[str, None] = "82e036d8a1a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blacklisted_tokens",
        sqlmodel.Column("id", postgresql.UUID(), nullable=False),
        sqlmodel.Column("is_deleted", sqlmodel.Boolean, nullable=True),
        sqlmodel.Column("created_at", sqlmodel.DateTime, nullable=True),
        sqlmodel.Column("updated_at", sqlmodel.DateTime, nullable=True),
        sqlmodel.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_blacklisted_tokens_id"), "blacklisted_tokens", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_blacklisted_tokens_id"), table_name="blacklisted_tokens")
    op.drop_table("blacklisted_tokens")
    # ### end Alembic commands ###
