"""added user model

Revision ID: 82e036d8a1a6
Revises:
Create Date: 2025-02-12 21:37:12.542897
"""

from typing import Sequence, Union
from alembic import op
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "82e036d8a1a6"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sqlmodel.Column("username", sqlmodel.String, nullable=True),
        sqlmodel.Column("email", sqlmodel.String, nullable=True),
        sqlmodel.Column("password", sqlmodel.String, nullable=True),
        sqlmodel.Column("is_active", sqlmodel.Boolean, nullable=True),
        sqlmodel.Column("is_superuser", sqlmodel.Boolean, nullable=True),
        sqlmodel.Column("id", postgresql.UUID(), nullable=False),
        sqlmodel.Column("is_deleted", sqlmodel.Boolean, nullable=True),
        sqlmodel.Column("created_at", sqlmodel.DateTime, nullable=True),
        sqlmodel.Column("updated_at", sqlmodel.DateTime, nullable=True),
        sqlmodel.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
