"""add_cascading_for_favourite_charchters

Revision ID: 9940180e3231
Revises: f852c9790b5d
Create Date: 2025-02-13 20:30:53.958880

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9940180e3231'
down_revision: Union[str, None] = 'f852c9790b5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_favorite_characters_user_id_fkey', 'user_favorite_characters', type_='foreignkey')
    op.drop_constraint('user_favorite_characters_character_id_fkey', 'user_favorite_characters', type_='foreignkey')
    op.create_foreign_key(None, 'user_favorite_characters', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_favorite_characters', 'lor_characters', ['character_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_favorite_characters', type_='foreignkey')
    op.drop_constraint(None, 'user_favorite_characters', type_='foreignkey')
    op.create_foreign_key('user_favorite_characters_character_id_fkey', 'user_favorite_characters', 'lor_characters', ['character_id'], ['id'])
    op.create_foreign_key('user_favorite_characters_user_id_fkey', 'user_favorite_characters', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
