"""add_constrain_unique_on_external_id

Revision ID: d345ea2fdf98
Revises: 9940180e3231
Create Date: 2025-02-13 20:51:45.373756

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd345ea2fdf98'
down_revision: Union[str, None] = '9940180e3231'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lor_characters_external_id', table_name='lor_characters')
    op.create_index(op.f('ix_lor_characters_external_id'), 'lor_characters', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lor_characters_external_id'), table_name='lor_characters')
    op.create_index('ix_lor_characters_external_id', 'lor_characters', ['external_id'], unique=False)
    # ### end Alembic commands ###
