"""added charchters model

Revision ID: f3fc21544577
Revises: 427e6fb33b3d
Create Date: 2025-02-13 15:47:56.675813

"""

from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f3fc21544577"
down_revision: Union[str, None] = "427e6fb33b3d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lor_characters",
        sa.Column("wikiUrl", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("race", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("birth", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("gender", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("death", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("hair", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("height", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("realm", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("spouse", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("external_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_lor_characters_external_id"),
        "lor_characters",
        ["external_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lor_characters_id"), "lor_characters", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_lor_characters_name"), "lor_characters", ["name"], unique=False
    )

    op.alter_column("users", "is_deleted", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column(
        "users", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        "users", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column("users", "username", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "email", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "password", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "is_active", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("users", "is_superuser", existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "is_superuser", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("users", "is_active", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("users", "password", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "email", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "username", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "users", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "users", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column("users", "is_deleted", existing_type=sa.BOOLEAN(), nullable=True)
    op.drop_index(op.f("ix_lor_characters_name"), table_name="lor_characters")
    op.drop_index(op.f("ix_lor_characters_id"), table_name="lor_characters")
    op.drop_index(op.f("ix_lor_characters_external_id"), table_name="lor_characters")
    op.drop_table("lor_characters")
    # ### end Alembic commands ###
