"""add_favourite_charchters

Revision ID: f852c9790b5d
Revises: 8e23a125c261
Create Date: 2025-02-13 18:41:02.191285

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f852c9790b5d'
down_revision: Union[str, None] = '8e23a125c261'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_favorite_characters', ['user_id', 'character_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_favorite_characters', type_='unique')
    # ### end Alembic commands ###
